
jwt:
  secret-key: ad861fbe42d6d4517997caaac85748c7b33ac43b0eb3d6fe19126eba998c1bb5c29f6110dd5e5d45c287462bc2cbd90865485e93e313717260b3a054c9d355a7
  token:
    expiration-time: 3600
    refresh-expiration-time: 2592000

oauth:
  kakao:
    client-id: f3474b073f9c02883e0b9ac53d7cbead
    url:
      auth: https://kauth.kakao.com
      api: https://kapi.kakao.com

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring
    username: root
    password: password
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  redis:
    host: localhost
    port: 6379

server:
  address: 0.0.0.0
  port: 8080